# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('referencia', models.IntegerField(verbose_name='Código do associado')),
                ('nome', models.CharField(max_length=100, verbose_name='nome associado')),
                ('endereco', models.CharField(blank=True, max_length=200, null=True, verbose_name='endereço')),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.CharField(blank=True, max_length=4, null=True)),
                ('pais', models.CharField(blank=True, max_length=25, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('celular2', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco_residencial', models.CharField(blank=True, max_length=200, null=True, verbose_name='endereço residencial')),
                ('bairro_residencial', models.CharField(blank=True, max_length=25, null=True)),
                ('cep_residencial', models.CharField(blank=True, max_length=10, null=True)),
                ('cidade_residencial', models.CharField(blank=True, max_length=25, null=True)),
                ('estado_residencial', models.CharField(blank=True, max_length=4, null=True)),
                ('pais_residencial', models.CharField(blank=True, max_length=25, null=True)),
                ('telefone_residencial', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('ano_de_formacao', models.IntegerField(blank=True, null=True, verbose_name='ano de formação')),
                ('historico', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cadastro de associado',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=35)),
                ('gera_financeiro', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ControlePresenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True, verbose_name='Presente')),
                ('associado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.Associado')),
            ],
            options={
                'verbose_name_plural': 'Controle de Presenças',
            },
        ),
        migrations.CreateModel(
            name='DataAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Data da aula',
                'verbose_name_plural': 'Datas das aulas',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_matricula', models.DateField(null=True, verbose_name='Data de matricula')),
                ('data_de_conclusao', models.DateField(null=True, verbose_name='Data de conclusão')),
                ('associado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.Associado')),
            ],
            options={
                'verbose_name_plural': 'Matriculas',
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55, verbose_name='Nome')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Cadastro de professores',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Seminario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('p', 'Palestra'), ('a', 'Aula'), ('s', 'Seminário')], default='s', max_length=10, null=True, verbose_name='Tipo')),
                ('vl_hora_aula', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor hora/aula')),
                ('professor', models.ManyToManyField(to='associados.Professores')),
            ],
            options={
                'verbose_name_plural': 'Cadastro de seminários e aulas',
            },
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulos', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Cadastro de títulos',
                'ordering': ('titulos',),
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data final')),
                ('seminario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associados.Seminario')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='seminario',
            name='seminario',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.Titulos'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.Turma'),
        ),
        migrations.AddField(
            model_name='dataaula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associados.Turma'),
        ),
        migrations.AddField(
            model_name='controlepresenca',
            name='data_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associados.DataAula'),
        ),
        migrations.AddField(
            model_name='associado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.Categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set([('associado', 'turma')]),
        ),
    ]
