# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0016_auto_20180201_1546'),
        ('associados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContasaReceber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('m', 'mensalidade'), ('s', 'seminario'), ('o', 'outros')], max_length=10, null=True, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_de_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_de_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associados.Associado')),
            ],
            options={
                'verbose_name_plural': 'Contas a receber',
            },
        ),
        migrations.CreateModel(
            name='ContasaReceberConsolidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('a', 'Aberto'), ('b', 'boleto gerado'), ('l', 'liquidado')], default='a', max_length=10, null=True, verbose_name='Status')),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_de_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_de_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('boleto_gerado', models.BooleanField(default=False, verbose_name='Boleto gerado?')),
                ('associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associados.Associado')),
                ('boleto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boleto.Boleto')),
            ],
            options={
                'verbose_name_plural': 'Contas a receber consolidado',
            },
        ),
        migrations.CreateModel(
            name='LancamentosMensais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_hora', models.IntegerField(verbose_name='Quantidade de aulas')),
                ('vl_hora_aula', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor hora/aula')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
                ('data_de_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de recebimento')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.Matricula')),
            ],
            options={
                'verbose_name_plural': 'Lançamentos mensais',
            },
        ),
        migrations.AddField(
            model_name='contasareceber',
            name='contas_areceber_consolidado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.ContasaReceberConsolidado'),
        ),
        migrations.AddField(
            model_name='contasareceber',
            name='lancamentos_mensais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.LancamentosMensais'),
        ),
        migrations.AddField(
            model_name='controlepresenca',
            name='lancamentos_mensais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='associados.LancamentosMensais'),
        ),
    ]
