# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0002_auto_20180202_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='data_de_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conclusão'),
        ),
    ]
