# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-02 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0003_auto_20180202_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasareceberconsolidado',
            name='boleto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
