# Generated by Django 2.0.2 on 2018-02-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associados', '0004_auto_20180202_0338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contasareceber',
            options={'verbose_name_plural': 'Lançamentos Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='contasareceberconsolidado',
            options={'verbose_name_plural': 'Contas a receber'},
        ),
        migrations.AlterField(
            model_name='contasareceber',
            name='tipo',
            field=models.CharField(blank=True, choices=[('m', 'mensalidade'), ('s', 'seminario'), ('m', 'multa'), ('v', 'vencimentos em atraso'), ('n', 'multa de vencimentos em atraso'), ('o', 'outros')], default='o', max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
