# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0002_auto_20171216_0232'),
        ('boleto', '0002_auto_20171209_2220'),
    ]

    operations = [
    ]
