# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0003_merge_20171216_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_banco', models.CharField(max_length=3, verbose_name='Código do Banco')),
                ('nome_banco', models.CharField(max_length=50, verbose_name='Nome do Banco')),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carteira', models.CharField(max_length=5)),
                ('aceite', models.CharField(default='N', max_length=1)),
                ('numero_documento', models.CharField(max_length=11, verbose_name='Ultimo Número do Documento')),
                ('agencia_cedente', models.CharField(max_length=4, verbose_name='Agência Cedente')),
                ('conta_cedente', models.CharField(max_length=7, verbose_name='Conta Cedente')),
                ('cedente', models.CharField(max_length=255, verbose_name='Nome do Cedente')),
                ('cedente_documento', models.CharField(max_length=50, verbose_name='Documento do Cedente')),
                ('cedente_cidade', models.CharField(max_length=255, verbose_name='Cidade do Cedente')),
                ('cedente_uf', models.CharField(max_length=2, verbose_name='Estado do Cedente')),
                ('cedente_endereco', models.CharField(max_length=255, verbose_name='Endereço do Cedente')),
                ('cedente_bairro', models.CharField(max_length=255, verbose_name='Bairro do Cedente')),
                ('cedente_cep', models.CharField(max_length=9, verbose_name='CEP do Cedente')),
                ('especie', models.CharField(default='R$', max_length=2, verbose_name='Espécie')),
                ('moeda', models.CharField(default='9', max_length=2)),
                ('local_pagamento', models.CharField(default='Pagável em qualquer banco até o vencimento', max_length=255, verbose_name='Local de Pagamento')),
                ('demonstrativo', models.TextField(blank=True)),
                ('instrucoes', models.TextField(default='1 - Não receber após 30 dias. \n2 - Multa de 2% após o vencimento. \n3 - Taxa diária de permanência de 0,2%.', verbose_name='Instruções')),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boleto.Banco')),
            ],
        ),
    ]
