# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0004_banco_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='especie_documento',
            field=models.CharField(blank=True, max_length=255, verbose_name='Espécie do Documento'),
        ),
    ]
