# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0005_conta_especie_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='demonstrativo',
        ),
    ]
