# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0006_remove_conta_demonstrativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='numero_documento',
            field=models.IntegerField(verbose_name='Ultimo Número do Documento'),
        ),
    ]
