# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0009_conta_codigo_transmissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='conta_cobranca',
            field=models.CharField(max_length=9, null=True, verbose_name='Conta Cobrança'),
        ),
        migrations.AddField(
            model_name='conta',
            name='digito_conta_cobranca',
            field=models.CharField(max_length=1, null=True, verbose_name='Dígito da Conta de Cobrança'),
        ),
    ]
