# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0010_auto_20171227_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='codigo_baixa',
            field=models.IntegerField(blank=True, choices=[(1, 'BAIXAR / DEVOLVER'), (2, 'NAO BAIXAR / NAO DEVOLVER'), (3, 'UTILIZAR PERFIL BENEFICIÁRIO')], default=1, null=True, verbose_name='Código para Baixa/Devolução'),
        ),
    ]
