# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0011_conta_codigo_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='prazo_baixa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Prazo para Baixa/Devolução'),
        ),
    ]
