# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0012_conta_prazo_baixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='codigo_juros',
            field=models.IntegerField(choices=[(1, 'Valor por dia'), (2, 'Taxa Mensal'), (3, 'Isento')], default=1, verbose_name='Código da multa'),
        ),
        migrations.AddField(
            model_name='conta',
            name='codigo_multa',
            field=models.IntegerField(choices=[(1, 'Valor fixo'), (2, 'Percentual')], default=2, verbose_name='Código da multa'),
        ),
        migrations.AddField(
            model_name='conta',
            name='juros_mora_taxa',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=8),
        ),
        migrations.AddField(
            model_name='conta',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=8, verbose_name='Valor/Percentual a ser concedido'),
        ),
    ]
