# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0013_auto_20171229_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='juros_mora_taxa',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=8),
        ),
    ]
