# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0014_boleto_juros_mora_taxa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='instrucoes',
            field=models.TextField(default='1 - Não receber após 30 dias. \n2 - Multa de 2% após o vencimento. \n3 - Taxa diária de permanência de {}.', verbose_name='Instruções'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='instrucoes',
            field=models.TextField(default='1 - Não receber após 30 dias. \n2 - Multa de 2% após o vencimento. \n3 - Taxa diária de permanência de {}.', verbose_name='Instruções'),
        ),
    ]
