# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleto', '0015_auto_20180102_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleto',
            name='instrucoes',
            field=models.TextField(default='1 - Não receber após 30 dias. \n2 - Multa de 2% após o vencimento. \n3 - Taxa diária de permanência de {:.2f}.', verbose_name='Instruções'),
        ),
    ]
